# Generated by Django 6.0.4 on 2026-04-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='current',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
