# Generated by Django 6.0.4 on 2026-04-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
