# Generated by Django 6.0.4 on 2026-04-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_category_transaction'),
        ('goals', '0004_goal_author'),
    ]

    operations = [
    ]
