# Generated by Django 6.0.4 on 2026-04-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_merge_0003_category_transaction_0004_goal_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goals/%Y/%m/%d/'),
        ),
    ]
