# Generated by Django 6.0.4 on 2026-05-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_transaction_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='goal',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
