# Generated by Django 6.0.4 on 2026-05-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_category_budgeted_remove_category_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budgeted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='category',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
