# Generated by Django 6.0.4 on 2026-05-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_category_budgeted_category_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reference_key',
            field=models.CharField(blank=True, db_index=True, max_length=320),
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
