# Generated by Django 6.0.4 on 2026-05-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_transaction_upcoming_and_notification_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='alert_type',
            field=models.CharField(choices=[('general', 'General'), ('budget', 'Budget'), ('upcoming', 'Upcoming')], default='general', max_length=16),
        ),
    ]
